# NumPy 1-D array 

In [2]:
#print the one dimentional array
import numpy as np

arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [3]:
#print the type of array

type(arr)

numpy.ndarray

In [6]:
#print the dimention of array
arr.ndim

1

# 2 - D array

In [8]:
#print the 2 dimentional array

arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [10]:
#print the type of array

type(arr2)

numpy.ndarray

In [12]:
#print the dimention of array
arr2.ndim

2

In [13]:
#print the size of the array

arr2.size

6

In [14]:
#print the shape of the array in (row,column) form

arr2.shape

(2, 3)

# ones matrix 

In [18]:
#Here we can print the float value of the 1-D array

mx = np.ones(5)
print(mx)

[1. 1. 1. 1. 1.]


In [20]:
#print the data type of the matrix
mx.dtype

dtype('float64')

In [21]:
#Here we can print the matrix with perticular row and column

mx2 = np.ones((4,5))
print(mx2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [23]:
#Here we can print the matrix with perticular row and column with particular datatype

mx3 = np.ones((2,3), dtype = int)
print(mx3)

[[1 1 1]
 [1 1 1]]


# Zeros matrix

In [25]:
#Here we can print the zeros matrix with paricular data type

mx4 = np.zeros((2,3),dtype = int)
print(mx4)

[[0 0 0]
 [0 0 0]]


In [30]:
#we know that 0's boolean value is false thats why it matrix will we false 
str_1 = 0
print(bool(str_1))

mx5 = np.zeros((3,4), dtype=bool)
print(mx5)

False
[[False False False False]
 [False False False False]
 [False False False False]]
