# NumPy Functions : 

In [1]:
import numpy as np

# arange()

In [5]:
#syntax : np.arange(start, ends , steps)
arr = np.arange(1,13,1)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


# reshape()

In [6]:
#print if we want to change the dimentions of arry then reshape() is used
arr_re = arr.reshape(3,4)
print(arr_re)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# ravel()

In [9]:
#This is convert the multi dimentional array into one-dimentional array
arr_re.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten()

In [11]:
#It is same as ravel() but in this function we can give the argument
arr_re.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# transpose()

In [12]:
#With this function we can transpose row into column and column into row
arr_re.transpose()

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])